# Generated by Django 4.2.6 on 2023-11-04 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_image_event_image1_event_image2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image1',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image3',
        ),
    ]
