# Generated by Django 4.2.6 on 2023-11-06 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_rename_image1_event_image_remove_event_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='event',
        ),
        migrations.AddField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='location',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='events.location'),
        ),
    ]
