# Generated by Django 4.2.6 on 2023-11-06 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_remove_location_event_event_image1_event_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
    ]
