# Generated by Django 4.2.6 on 2023-11-06 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_city_location_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='city',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='event',
            name='image2',
        ),
    ]
