# Generated by Django 4.2.6 on 2023-11-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_remove_event_city_remove_event_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='city',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
