# Generated by Django 4.2.6 on 2023-11-06 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_event_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='photos/events'),
        ),
        migrations.AddField(
            model_name='event',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='photos/events'),
        ),
    ]
