# Generated by Django 4.2.6 on 2023-11-10 16:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_event_image1_event_image2'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='start_time',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
