# Generated by Django 4.2.6 on 2023-11-14 17:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_alter_event_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ending_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='event',
            name='renewal_email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
