# Generated by Django 4.2.6 on 2023-11-15 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0012_event_ending_time_event_renewal_email_sent'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/event_menu')),
                ('is_active', models.BooleanField(default=True)),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicer_menu', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
