# Generated by Django 4.2.6 on 2023-11-22 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventbooking',
            old_name='number_of_members',
            new_name='numberOfMembers',
        ),
    ]
