# Generated by Django 4.2.6 on 2023-11-28 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_remove_eventbooking_booking_order_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventbooking',
            name='menus',
            field=models.JSONField(default=dict),
        ),
    ]
