# Generated by Django 4.2.6 on 2023-11-28 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_alter_eventbooking_menus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='status',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20),
        ),
    ]
