# Generated by Django 4.2.6 on 2023-11-28 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_remove_eventbooking_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventbooking',
            name='menus',
        ),
        migrations.AddField(
            model_name='eventbooking',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('complete', 'Complete'), ('cancelled', 'Cancelled'), ('returned', 'Returned')], default='pending', max_length=20),
        ),
    ]
