# Generated by Django 4.2.6 on 2023-10-29 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servicer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(default='', max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('mobile_no', models.CharField(default='', max_length=100)),
                ('is_active', models.BooleanField(default=False)),
                ('is_servicer', models.BooleanField(default=False)),
            ],
        ),
    ]
