# Generated by Django 4.2.6 on 2023-12-05 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_profile',
            field=models.BooleanField(default=False),
        ),
    ]
