# Generated by Django 4.2.6 on 2023-11-19 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('servicer', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('events', '0013_eventmenu'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requirement', models.TextField(blank=True, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('new_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('reason', models.TextField(blank=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.event')),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicer', to='servicer.servicer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TransactionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('commission', models.PositiveIntegerField(blank=True, null=True)),
                ('total_amount', models.PositiveIntegerField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='user.eventsorder')),
                ('servicer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicers', to='servicer.servicer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
